#+TITLE: Algorithms & Data Structures: From Physics to Society
#+TAGS:
** TODO make new tags autoadd to #+TAGS:
** TODO go through this document while rereading the org manual!!

* Heuristic
- do something quantative where possible (learn data scraping, statistics)

* Topic Ideas
** Thesis: The Addoption Sucess of "superior technology" is first order in reagrds to the efficiency of the learning environment :thesis:
- "a Gui is just an inbuit tutorial"
*** TODO make quotes work better (use the tags)

** A Review of Diagram Communication
- what diagrams are used
- what information can they represent
** On Keyboards
- the left today are gleeful to exclaim that just about everything from common sense to men is the product of wetern imperialism, one thing that actually is, is keyboards.
  + had the chinese invented keyboards....

** Timeline Exploerers
Natural way of exploring data, why aren't they more common
- Example: developmental psychology timeline of children learing abilities

** On Scientific Papers (and technical writing)
- every paper should come with a github repository. The frontier of science is computations
- interactivity (bret victor)
- citations should be sortable by most recommended to least, by tag (auto generated), by citations etc,  
- all of this would probably require a journal to inforce these new standards on the writer
- commenty should be part of the package 
- ideas are the first class citizens (ideas = datastructure+algorithm (macro))
- Problem: semantic overloading, clear definitions are not always stated
  + NOT an easy problem to solve in english, you 
- incentive to over publish. Wouldnt it be nice if people only published when they actually discovered somthing, rather than paying people to make something up x times a year every year

** On Democracy
- P1. we dont live in very democratic democracies
- Options:
  a) democracy is good -> democracy++
  b) democracy is bad -> democracy--
  c) the illusion of democracy is good but democracy is bad -> democracy--
  d) is complicated -> we have a serious conversation about the nature of democracy

** On universities
- we need to conceptually split 1) education & 2) research

*** Education

*** Research
**** Research vs Industry

** On Cognitive Science
- what is its place? [citeeeeeeeee decline of cogsci!!]
- define the goals
- the definition is not to broard, but not broard enough
  + we need to resurect some more ancient ideas of knowledge
  + we can fold everything! into the definiton of congnitive science
- *Meta-progress* indirect  :concept:
  + e.g. doing things that allow cognitive science to improve- personal productivity, the stucture of academia, lifespan etc.

*** Meta-Cogntive Science
- a new branch of cognitive science based on derivatives.
- indirectly attacking the engineering problem of ai and cognition
- we need to build models of the models

** On Tech, Silicon Vally and Startup Culture
- Assumption: great stagnation, tyler cowan, peter tiel 
- the one area of society there has been progress in in tech
- where did this progress come from?
  + technological improvements: mores law etc.. 
  + 2nd order tools, vc funding, mindset, github, culture
- if the second then this is exportable to the rest of culture society and industry


** Wolfram Physics Project for the Mind?

** Rice(ing) (Race Inhancment Consmetic Effects)

*** History
"(tag as history, you wan this as an openable window) Ricing was initiated by Asian street racers customizing their vehicles with stickers, paints, spoilers and other accessories to make their car look cool. Some do it even to stand out and/or “go faster” (meant to make them feel like their faster I guess, if that were the case, then the top car making companies should just do the same). It wasn’t invented/coined by them as it was mostly used as an insult for a while.

The term “RICE” stands for Race Inspired Cosmetic Enhancment. A group of people (could be one, idk) decided to see if they could tweak their own distros like they/others did their cars. This gave rise to a community of Linux/Unix enthusiasts trying to make their distros look cooler and better than others."

*** Problem:
Software Ricing, in addopting the cheap connotations of its boy-racer namesake is holding back the ricing community from understanding its beauty and significance in the world. The idea of enhancements being cosmetic and merely consmetic for cosmetic sake rather than practical, productive, useful and inherently valuable. means of  

- History: british technical workshops at the dawn of the industrial revolution
- its the only place were people still tinker

*** New Idea: Rice and Peas
- peas arent really peas, their beans
- beans are protien- they make you grow strong


* The Structure of Documents

** Literate Programming

** Inspectable Elements (game design)

** Metadata



* Data Structures vs Data and Structures
- which should be in the title?

* Quotes

** Wittgenstein

** All Other
"Before there were computers, there were algorithms, but now there are computers there are even more algorithms" - CLRS chap 0


* Reading List
- Joshua Bach
- Wittgenstein
- Karl Frixton
- Donald E. Knuth
