#+TITLE: BA BArbados complaint 01/2021

Dear British Airways,

I am writing to complain and seek compensation and explanation for the series of events I was subject to upon attempting to leave Edinburgh airport for Bridgetown Barbados (via London Heathrow) on the 2nd of January (BA1435, 02/01/2021).

As you might be aware, the Barbados government had certain requirements for travelers to the country at this time. Specifically all entrants must have had a negative PCR test within 3 days of travel so I booked myself an appointment to get privately tested on the 31st (at great difficulty and expense due to new years closures). However, I had spent Christmas with my family and soon after (evening of the 28th) it turned we had been in direct contact with persons who tested positive for Covid-19, so we all had to arrange to get tested with the NHS.

As by this time was no longer with my family and isolating alone, I naturally realised that if I took my NHS test the next day (29th), and it came back negative, it could double up as a test for my flight. At the time, I briefly reread the relevent documentation, both the British Airways guidance and the Barbados Government regulations, then cross-checked my understanding with my father, a doctor, who assured me that I was well within regulation (not to metion   common sense) to potentially use my test for both purposes and moreover he pointed out that the the British governments rules are that you should not under any circumstances seek a private test if you are symptomatic or have been in contact with someone who was (as I had been).

Upon arrival at Edinburgh airport I was faced with two young women, Linzi and Shelly on the BA front desk who would not let me board my flight with my NHS test. Both of them were exceedingly rude and disrespectful to me as a customer, speculating and slanderous of my reason for having an NHS test, not to mention unhelpful and utterly unable to answer my questions coherently on why this was the case, and what my travel options were. In addition to my wider claim against being restricted from flying without due cause, I would also like to raise a formal complaint agaist both Linzi and Shelly, primarily for rudeness, slander and inhospitable service-- specifically Linzi.

The content of their reasoning as to why I could not board was as follows—

First Shelly/Linzi claimed that

    Claim (1) : “the system will not let me check you in with an NHS test”.

As the Barbadian Government has no specific requirements for an NHS test (and nor did the British Government at this time, see following for discussion), for this to be true, there would have to be an explicit specification on the BA check-in interface requiring that the test not be an NHS test leading us to the following conclusion from Claim (1)

    Conclusion (1) : Not allowing NHS tests is a BA specific policy.

Assuming Conclusion (1), customers could expect to have this conveyed to them in the special guidlines issued BA (it wasn't to my knowledge). Hence, under Conclusion (1), BA is responsible for me missing my flight and all reasonable costs incured as per the  associated with it.

Upon me inquiring as to whether this was explicit BA policy, she refused to answer and we were soon joined by her manager (Linzi) who also refused to answer directly. Upon futher inquiry they found and begun quoting British Government's website which mentioned in the middle of a secondary paragraph, "you should not use the NHS to arrange your test" (the website has since been updated and replaced this advice).





y    mention this in their



British gov quote



Why it’s wrong



Claim that they would get finned (by why about what)



My suspicions at the time



Aftermath

Wouldn’t let me board the flight to London (completely legal) and phone forward to deal with it there

Wouldn’t let be buy a ticket to London (claiming there was no time)

Gave me wrong unnumbered



Next day they let the person infringe of me on a flight to America with an NHS test, when I questioned the lady on this, explaining that I had been rejected on similar





 I thought nothing of it as common sense would dictate that there is nothing ‘special about a pro





~ ba quote ~



- souce
